apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleforum-notification-service-deploy

spec:
  template:
    metadata:
      labels:
        app: simpleforum-notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: simpleforum-notification-service
        env:
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -javaagent:/pinpoint-agent/pinpoint-bootstrap.jar
            -Dpinpoint.applicationName=DEV_SIMPLE_NOTIFICATION
            -Dpinpoint.agentId=devsimplenotify
            -Dpinpoint.profiler.profiles.active=release
        volumeMounts:
        - mountPath: /logs
          name: logback
      volumes:
      - name: logback
        hostPath:
          path: /var/log/logback/dev/simpleboard/notification-service