apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleforum-user-service-deploy

spec:
  template:
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -javaagent:/pinpoint-agent/pinpoint-bootstrap.jar
            -Dpinpoint.applicationName=DEV_SIMPLE_USER
            -Dpinpoint.agentId=devsimpleuser
            -Dpinpoint.profiler.profiles.active=release