apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
patchesStrategicMerge:
- ./deployment-patches.yaml

images:
- name: yellowsunn/simpleforum-user-service
  newTag: SNAPSHOT-20240313225019
resources:
- ../../base
