apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
patchesStrategicMerge:
- ./deployment-patches.yaml

images:
- name: yellowsunn/simpleforum-image-service
  newTag: SNAPSHOT-20240312233645
resources:
- ../../base
