apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
patchesStrategicMerge:
- deployment.yaml
- hpa-patches.yaml

images:
- name: yellowsunn/login-msa-auth-app
  newTag: SNAPSHOT-20230315205554
resources:
- ../base
