apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
images:
- name: harbor.yellowsunn.com:80/test/spring-boot-example
  newTag: "20231024230343"
