apiVersion: v1
kind: Service
metadata:
  name: spring-boot-example-svc
spec:
  ports:
    - name: web-port
      port: 80
      targetPort: 8080
  selector:
    app: spring-boot-example
  type: LoadBalancer
