apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
patchesStrategicMerge:
- ./hpa.yaml

images:
- name: yellowsunn/simpleforum-board-service
  newTag: SNAPSHOT-20240310005120
resources:
- ../../base
