apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/logback/**/*.log
      tag logback
      multiline_flush_interval 1s
      <parse>
        @type multiline
        format_firstline /^\[\w+\s*\]/
        format1 /^\[(?<log.level>\w+)\s*\] \[(?<log.timestamp>.+)\] \[(?<service.name>.+)\] \[(?<service.profile>.+)\] \[(?<service.thread>.+)\] (?<log.logger>.+) - (?<message>.*)/
      </parse>
    </source>
    
    <match logback>
      @type elasticsearch
      host 10.10.10.27
      port 9200
      <buffer>
        @type memory
        timekey 3s
        timekey_wait 0s
        flush_interval 3s
      </buffer>
    </match>
