apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/logback/**/*.log
      tag logback
      multiline_flush_interval 1s
      <parse>
        @type multiline
        format_firstline /^\[\w+\s*\]/
        format1 /^\[(?<level>\w+)\s*\] \[(?<timestamp>.+)\] \[(?<service.name>.+)\] \[(?<profile>.+)\] \[(?<thread>.+)\] (?<class>.+) - (?<message>.*)/
      </parse>
    </source>
    
    <match logback>
      @type elasticsearch
      host 10.10.10.27
      port 9200
    </match>
