apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  template:
    metadata:
      name: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: 'true'
            - name: KAFKA_CLUSTERS_0_NAME
              value: prod-kafka
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: 10.10.10.35:9092,10.10.10.36:9092,10.10.10.37:9092
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: 10.10.10.32:2181,10.10.10.33:2181,10.10.10.34:2181
